---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sonypufv/system.lumisktechnology.com
    - /bin/cp -Rf . $DEPLOYPATH
    - cd $DEPLOYPATH && php composer.phar install --no-dev --optimize-autoloader
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
